### ISSUE TITLE
Rails 2.3?

### ISSUE THREAD

**Issue by PhilT** [moonmaster9000/dupe#15]
The readme indicates Rails 3 support is to be added and yet installing the gem installs activesupport and activemodel 3. I tried 0.3.5 but that's the same. Does this gem still work with Rails 2.3?

Thanks.

**Comment by moonmaster9000** [comment]
Hi, 

Sorry, thanks for reporting this! It looks like the gemspec just says activeresource>=2.3.3, and when rails 3 went out of beta (--pre), it just started using rails 3. I'll update the gemspec and push a new version. Thanks!

**Comment by moonmaster9000** [comment]
ok, it's fixed and released to rubygems.org. version 0.5.3.

**Comment by PhilT** [comment]
Thanks!
