### ISSUE TITLE
Getting a URI::BadURIError: both URI are relative

### ISSUE THREAD

**Issue by lporras** [moonmaster9000/dupe#18]
When I try to do this:

Dupe.create :author, :name => 'Tiger', :published => false

class Author < ActiveResource::Base; self.site = ''; end

Get %r{/authors/published.xml} do
  Dupe.find(:authors) {|a| a.published == true}
end

Author.find :all, :from => :published

Finally I get: URI::BadURIError: both URI are relative
from lib/dupe/active_resource_extensions.rb:19:in `get'

I am using rails 3.0.5 and dupe '0.6.0', and ruby 1.8.5... Should I use ruby 1.9.X?

**Comment by lporras** [comment]
I just try with ruby-1.9.2 y ruby 1.8.7 and this still happens, what could it be?

**Comment by moonmaster9000** [comment]
i think in previous versions of activeresource, you could set self.site='' and it would still work in test mode. in rails 3.0.5, you'll need to set self.site to something other than an empty string. (if you're just testing it out, then set it to anything; try self.site = 'http://localhost')

**Comment by lporras** [comment]
thanks it works and congrats Dupe is awesome
