### ISSUE TITLE
Rails 3.1 support

### ISSUE THREAD

**Issue by cgriego** [moonmaster9000/dupe#19]
Rails 3.1 is right around the corner but I wasn't able to use Dupe with the edge version of Rails. I got a lot of errors.

**Comment by moonmaster9000** [comment]
thanks. wanna try to upgrade it and send a pull request? i have little bandwidth right now to work on dupe. thanks!

**Comment by moonmaster9000** [comment]
version 1.0.0 supports rails 3.1
