### ISSUE TITLE
Dupe only called when Resources not existing

### ISSUE THREAD

**Issue by ghost** [moonmaster9000/dupe#22]
It seems that while Dupe is loaded, all ActiveResource requests are processed by Dupe.

I think it would be interesting that Dupe act as a backup so that normal requests with different uri than those defined with Dupe keep being processed as normal active resources. If a NoResource error is raised by ActiveResource, then Dupe is asked for a mock resource corresponding.

That way, resources can be mocked while others are kept real.

**Comment by moonmaster9000** [comment]
I agree, can you put together a pull request?
