### ISSUE TITLE
No free intercepts when using a url like http://host/api/v1

### ISSUE THREAD

**Issue by bloudermilk** [moonmaster9000/dupe#8]
When my ActiveResource objects are configured to use non-root URLs like `http://host/api/v1`, Dupe doesn't know how to create the standard CRUD intercepts. It knows to look at at the right URL when `.find()`ing, but returns this error:

```
HANDLER ERROR: No mocked service response found for '/api/v1/users/1.xml'
```

This is easily solved on my side by simply removing everything after `http://host/`, but it would be nice if there was built in support for this.

**Comment by moonmaster9000** [comment]
ah ok i think i c what the problem is. thanks for reporting it! i'll fix it this weekend.

**Comment by bloudermilk** [comment]
No problem! Dupe has a been a huge help so far in my attempt to TDDize one of my APIs

**Comment by moonmaster9000** [comment]
hi brendan, 

i'm having trouble duplicating this problem (i'm using Dupe 0.5.1):

<pre>
  &gt;&gt; require 'dupe'
  =&gt; true
  
  &gt;&gt; class Book &lt; ActiveResource::Base; self.site='/api/vi'; end
  =&gt; "/api/vi"
  
  &gt;&gt; Dupe.define :book 
  =&gt; #&lt;Dupe::Model:0x198aa20 @id_sequence=#&lt;Sequence:0x198a9e4 @current_value=1, @transformer=nil&gt;, name:book, schema#&lt;Dupe::Model::Schema:0x198a9f8 @after_create_callbacks=[], @attribute_templates={}&gt;
  
  &gt;&gt; Book.site
  =&gt; #&lt;URI::Generic:0x198c6f4 URL:/api/vi/&gt;
  
  &gt;&gt; Book.prefix
  =&gt; "/api/vi/"
  
  &gt;&gt; Dupe.create :book
  =&gt; &lt;#Duped::Book id=1&gt;
  
  &gt;&gt; Book.find 1
  =&gt; #&lt;Book:0x1967f34 @attributes={"id"=&gt;1}, prefix_options{}
  
  &gt;&gt; puts Dupe.network.log.pretty_print
  Logged Requests:
    Request: GET /api/vi/books/1.xml
    Response:
      &lt;?xml version="1.0" encoding="UTF-8"?&gt;
      &lt;book&gt;
        &lt;id type="integer"&gt;1&lt;/id&gt;
      &lt;/book&gt;
</pre>

**Comment by bloudermilk** [comment]
Ahhh, my mistake. This came from the fact that I was including the full url path in a custom `.find()` call like:
    Book.find(:all, :from => "http://hostname/author/#{author_id}/books.xml")
Once I formatted that call like so:
    Book.find(:all, :from => "/author/#{author_id}/books.xml")
it worked.

Thanks and sorry for wasting your time!
